const PlannerActionTypes = {
  AUTOCOMPLETE_START: 'AUTOCOMPLETE_START',
  AUTOCOMPLETE_SUCCESS: 'AUTOCOMPLETE_SUCCESS',
  AUTOCOMPLETE_FAILURE: 'AUTOCOMPLETE_FAILURE',
  SET_ORIGIN: 'SET_ORIGIN',
  SET_DEST: 'SET_DEST',
  DIRECTIONS_START: 'DIRECTIONS_START',
  DIRECTIONS_SUCCESS: 'DIRECTIONS_SUCCESS',
  DIRECTIONS_FAILURE: 'DIRECTIONS_FAILURE',
};

export default PlannerActionTypes;